apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gotd
  name: bot
  labels:
    app: bot
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      volumes:
        - name: cache
          emptyDir: {}
      containers:
        - name: bot
          image: ghcr.io/gotd/bot:main
          env:
            - name: HOME
              value: /cache
            - name: HTTP_ADDR
              value: 0.0.0.0
            - name: METRICS_ADDR
              value: 0.0.0.0
            - name: TG_NOTIFY_GROUP
              value: gotd_ru
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: BOT_TOKEN
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: APP_ID
            - name: APP_HASH
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: APP_HASH
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: GITHUB_PRIVATE_KEY
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: GITHUB_SECRET
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: GITHUB_APP_ID
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: GITHUB_CLIENT_ID
          volumeMounts:
            - mountPath: /cache
              name: cache
