kind: Service
apiVersion: v1
metadata:
  namespace: gotd
  name: bot
spec:
  selector:
    app: bot
    prometheus: "true"
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 8080
      protocol: TCP
      targetPort: 8090
      name: metrics
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot
  namespace: gotd
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: status
spec:
  rules:
    - host: bot.gotd.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bot
                port:
                  name: http
